### ISSUE TITLE
Modal: Close button icon is misaligned

### ISSUE THREAD

**Issue by craigcarlyle** [Doist/reactist#566]
### Current behaviour

The close modal button seems to be misaligned when used in Twist:

![Screen Shot 2021-09-20 at 11 09 39 AM](https://user-images.githubusercontent.com/1305500/134052746-58b66996-1521-4721-898b-7b4a3afd9202.png)

### Expected behaviour

The icon should be aligned

### Possible solutions

Remove the following from `modal.module.css`:

```css
.closeButtonIcon {
    margin-left: -4px;
    margin-top: -3px;
}
```
